### ISSUE TITLE
New stylesheet for design

### ISSUE THREAD

**Issue by lainecedes** [briannededeugd/techapplication#10]
This issue has been opened to work on the stylesheet, which we will use later to design the app.
The sheet is currently being made by both Bryan and I, and this will show up in the group app in PDF format (or wiki) today (hopefully at least) so we can move on from there.

If you would like to access the XD file and make changes, I will need your email address.

**Comment by briannededeugd** [comment]
Hey, could you invite me to the XD file? My email is brianne@live.nl !

**Comment by JarnoVoogd** [comment]
very nice, thanks for the invite!

**Comment by lainecedes** [comment]
Stylesheet has been made!
