### ISSUE TITLE
Project template complete

### ISSUE THREAD

**Issue by JarnoVoogd** [briannededeugd/techapplication#4]
Hi all, 

The project template has been completed. Each team members' feature has a seperate working route, you can use this route to write your code in. This way we can keep all our code seperated in different files, even though we'll be working in different branches. 

Speaking of branches, there is now a branch for each team member and his/her feature. Everyone will work in their own branch and their own file, this will make the merging process a lot easier. 

All you have to do is clone the repository,  add the .env file that I sent privately and install all the packages mentioned in the package.json. If this doesn't work, if you don't have a node_modules folder, run npm init and retry the previous steps. This should work.

When all is done you can check into your own branch and start implementing your feature into this code.

**Comment by TristanBrattinga** [comment]
Followed all steps and starting with making the register route

**Comment by TristanBrattinga** [comment]
Hi Team, everyone integrated the template and is starting with building out the routes. Part succesful so closing issue!
