### ISSUE TITLE
Database available for use

### ISSUE THREAD

**Issue by briannededeugd** [briannededeugd/techapplication#5]
Hey team,

A basic set-up of the database in MongoDb has been completed, which you all have access to. Beware, you need to be in the **teamtech** project for the **teamapplication** database. There's two collections inside of it; one for 'songs' and one for 'users'. Tristan will be using the 'users' collection for the registering feature, the basis on which all of you will eventually build your own feature. The 'songs' collection is currently only being used for the matching feature.

For your feature to work with the database, it is important for you to create your own `.env` file as Jarno mentioned [in the previous issue](https://github.com/briannededeugd/techapplication/issues/4). Its required content has been sent in our groupchat for security, so all you have to do is copy and paste.

That's it for now. Good luck taking the first steps!

**Comment by TristanBrattinga** [comment]
Hi Team, everyone has incorporated the database, so closing this issue
